version: '3'
volumes:
  pgdata:
  pgadmin:
services:
  php:
    build: ./docker/php
    volumes:
      - ./docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./www:/var/www:cached
    working_dir: /var/www
  nodejs:
    build: ./docker/nodejs
    volumes:
      - ./www:/var/www:cached
      - ./www/node_modules:/var/www/node_modules:delegated
    working_dir: /var/www
    tty: true
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www:cached
    ports:
      - 8080:80
    depends_on:
      - php
    working_dir: /var/www
  postgres:
    build: ./docker/postgres
    restart: always
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  redis:
    image: redis:alpine
    ports: 
      - 16379:6379
